// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Icon: typeof import('./components/Icon.vue')['default']
    Menu: typeof import('./components/Menu.vue')['default']
    MyForm: typeof import('./base-ui/myForm.vue')['default']
    MyTable: typeof import('./base-ui/myTable.vue')['default']
    NotFont: typeof import('./components/NotFont.vue')['default']
  }
}

export { }
